export const TeamMembers = [
  {
    name: 'Swasthik Shetty',
    role: 'Technical Head | Full Stack Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Nagaraj Pandith',
    role: 'Frontend Lead | Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Prayag Sharma',
    role: 'Technical Head | Management',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Numan Naeem',
    role: 'UI Lead | Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Satvik Nayak',
    role: 'Frontend Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Aaron Nazareth',
    role: 'Backend Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Keerthan N S',
    role: 'Frontend Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Padmashree Shetty',
    role: 'Backend Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
  {
    name: 'Kumar Ankush',
    role: 'Frontend Developer',
    image: '',
    github: '',
    linkedin: '',
    instagram: '',
    quote: '',
  },
];
