export const events = [
  {
    id: "1",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
  },
  {
    id: "2",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CSE",
  },
  {
    id: "3",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CSE",
  },
  {
    id: "4",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "EEE",
  },
  {
    id: "5",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CC",
  },
  {
    id: "6",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CORE",
  },
  {
    id: "7",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
  },
  {
    id: "8",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
  },
];
