export const events = [
  {
    id: "1",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
    venue: "Online",
    rounds: 3,
    price: 60,
  },
  {
    id: "2",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CSE",
    venue: "ISL02",
    rounds: 3,
    price: 50,
  },
  {
    id: "3",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CSE",
    venue: "ISL02",
    rounds: 3,
    price: 20,
  },
  {
    id: "4",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "EEE",
    venue: "ISL02",
    rounds: 3,
    price: 10,
  },
  {
    id: "5",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CC",
    venue: "ISL02",
    rounds: 3,
    price: 0,
  },
  {
    id: "6",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "CORE",
    venue: "ISL02",
    rounds: 3,
    price: 200,
  },
  {
    id: "7",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
    venue: "ISL02",
    rounds: 3,
    price: 100,
  },
  {
    id: "8",
    name: "Hello world",
    date: "12/05/2023",
    image: "https://spotme.com/wp-content/uploads/2020/07/Hero-1.jpg",
    link: "#",
    branch: "ISE",
    venue: "ISL02",
    rounds: 3,
    price: 0,
  },
];
